### ISSUE TITLE
[papirus-sddm-theme] delete sddm-kcm dependency

### ISSUE THREAD

**Issue by Doaxan** [PapirusDevelopmentTeam/PKGBUILDs#3]
Please delete **sddm-kcm** dependency to make work theme without installing KDE packages. KDE already have **sddm-kcm**.

**Comment by FadeMind** [comment]
Fixed via: 
https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-sddm-theme-git&id=72da960327b853ad4f75191217fbef113a011311

and 

https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-sddm-theme&id=3e55ca178f69cf312d6b9773ec24dfe72f4f8ff6
